package com.qa.portfolio;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;

/**
 * Test file for FizzBuzz Class.
 * 
 * Run this file to assess progress.
 * 
 * DO NOT EDIT THIS FILE!
 * 
 */
public class FizzBuzzTest {

	private FizzBuzz answers;
	
	@Before
	public void setup() {
		answers = new FizzBuzz();
	}
		
	@Test
	public void fizzTest() {
		assertEquals("fizz", answers.fizzBuzz(12));		
	}
	
	@Test
	public void buzzTest() {
		assertEquals("buzz", answers.fizzBuzz(40));		
	}
	
	@Test
	public void fizzBuzzTest() {
		assertEquals("fizzbuzz", answers.fizzBuzz(120));		
	}
	
	@Test
	public void neitherFizzOrBuzzTest() {
		assertEquals("8", answers.fizzBuzz(8));	
	}
}
