package com.qa.portfolio;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Test file for MultiChar Class.
 * 
 * Run this file to assess progress.
 * 
 * DO NOT EDIT THIS FILE!
 * 
 */
public class MultiCharTest {
	
	private MultiChar answers = new MultiChar();
	
	@Test
	public void theTest() {
		assertEquals("TTThhheee", answers.multiChar("The"));
	}
	
	@Test
	public void singleLetterTest() {
		assertEquals("AAA", answers.multiChar("A"));
	}
	
	@Test
	public void punctuationTest() {
		assertEquals("HHHiii---TTThhheeerrreee", answers.multiChar("Hi-There"));
	}

}
