package com.qa.portfolio;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Before;
import org.junit.Test;

/**
 * Test file for EvenlySpaced Class.
 * 
 * Run this file to assess progress.
 * 
 * DO NOT EDIT THIS FILE!
 * 
 */
public class EvenlySpacedTest {

	private EvenlySpaced answers;

	@Before
	public void setup() {
		answers = new EvenlySpaced();
	}

	@Test
	public void evenlySpacedEvenTest() {
		assertTrue(answers.evenlySpaced(2, 4, 6));
	}

	@Test
	public void evenlySpacedDifferentOrder() {
		assertTrue(answers.evenlySpaced(4, 6, 2));		
	}

	@Test
	public void evenlySpacedOddTest() {
		assertTrue(answers.evenlySpaced(3, 7, 11));
	}
	
	@Test
	public void notEvenlySpaced() {
		assertFalse(answers.evenlySpaced(4, 10, 8));		
	}
	
	@Test
	public void notEvenlySpacedWithOddNumbers() {
		assertFalse(answers.evenlySpaced(5, 11, 8));		
	}

}
